repository:
  # Repository name
  name: swarm-decision-framework
  
  # Repository description
  description: A Swarm-Powered Decision Framework using OpenAI's Swarm library
  
  # Enable issues, projects, and wiki
  has_issues: true
  has_projects: true
  has_wiki: true
  
  # Default branch (should match your actual default branch)
  default_branch: main
  
  # Allow squash merging pull requests
  allow_squash_merge: true
  # Disable merge commits
  allow_merge_commit: false
  # Allow rebase merging
  allow_rebase_merge: true
  
  # Delete head branches after merging pull requests
  delete_branch_on_merge: true

# Branch protection rules
branches:
  - name: main
    protection:
      # Require pull request reviews
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      
      # Require status checks to pass
      required_status_checks:
        strict: true
        contexts:
          - "test"
      
      # Enforce all restrictions for administrators
      enforce_admins: true
      
      # Restrict who can push to this branch
      restrictions: null  # null means any user with push access
      
      # Require signed commits
      required_signatures: true
      
      # Require linear history
      required_linear_history: true
      
      # Allow force pushes
      allow_force_pushes: false
      
      # Allow deletions
      allow_deletions: false

# Labels for issues and pull requests
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  
  - name: enhancement
    color: a2eeef
    description: New feature or request
  
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  
  - name: question
    color: d876e3
    description: Further information is requested
  
  - name: wontfix
    color: ffffff
    description: This will not be worked on
