name: decision-framework-dev

channels:
  - conda-forge
  - defaults

dependencies:
  # Base Python environment
  - python=3.12
  
  # Development tools
  - ipython=8.18.1
  - jupyter=1.0.0
  - black=24.1.1
  - flake8=7.0.0
  - mypy=1.8.0
  - pytest=8.0.0
  - pytest-cov=4.1.0
  - pre-commit=3.6.0

  # Configuration and Environment Management
  - python-dotenv=1.0.0
  - pyyaml=6.0.1

  # Documentation generation
  - sphinx=6.2.1
  - sphinx-rtd-theme=1.2.2
  - recommonmark=0.7.1
  - pandoc=3.1.3
  - docutils=0.18.1
  - watchdog=3.0.0
  
  # Package management
  - pip=23.3.1
  - conda-lock=2.5.1
  
  # Security
  - bandit=1.7.7

  # Additional documentation tools via pip
  - pip:
    - sphinx-autobuild==2024.2.4
    - m2r2==0.3.3.post2
    - sphinx-markdown-tables==0.0.17
    - sphinx-copybutton==0.5.2
